Updated p2p tutorial to use new messages api
GodotSteam/GodotSteam-Docs pull request #43
Opened 2024-12-06 07:36 UTC by BrianBHuynh

Now this uses the new steam messages api which should be route networking through steam servers which should be better for privacy and ping if steam is to be believed

2024-12-07 18:51 UTC, Gramps requested changes
I think the lobby tutorial might need updating in tandem with this one to prevent confusion.  I will have to review that one this coming week to see where it might need punched up.

2024-12-07 18:51 UTC, Gramps commented on docs/tutorials/p2p.md
> +Here is a nice bit of code from **Toi Lanh** based on **tehsquidge**'s networking code for handling packet reading:
There is no packet limiting here though.  This should be removed entirely as it is shown above.

2024-12-07 18:51 UTC, Gramps commented on docs/tutorials/p2p.md
> +Inside that handshake there was a call to the `read_messages()` function which does this:
The lobby tutorials would need to be updated to reflect this.  Preferably with tabbed versions of code for each class.  Also the lobby tutorial needs update as the handshake process has changed a bit in the newest, suggested version from Skillet.

2024-12-07 18:51 UTC, Gramps commented on docs/tutorials/p2p.md
> +func _on_network_messages_session_failed(steam_id: int, session_error: int, state: int, debug_msg: String) -> void:
This section should be fleshed out more to show the possible errors and what to do with the other variables.

2024-12-07 18:51 UTC, Gramps commented on docs/tutorials/p2p.md
> +func _on_network_messages_session_request(remote_id: int) -> void:
A variant of this with ban lists:
```
func _on_network_messages_session_request(this_steam_id: int) -> void:
	Logging.write(name, "Incoming Messages session request from :%s" % this_steam_id)
	if this_steam_id > 0:
		if this_steam_id in lobby_ban_list:
			print("This user is in the player's ban list: %s" % this_steam_id)
		else:
			if not Steam.acceptSessionWithUser(this_steam_id):
				print("Failed to accept Messages session with: %s" % this_steam_id)
			else:
				print("Accepted Messages session with: %s" % this_steam_id)
	else:
		print("The requesting user had an invalid Steam ID: %s" % this_steam_id)
```

2024-12-07 18:51 UTC, Gramps commented on docs/tutorials/p2p.md
> +				# Append logic here to deal with message data. Do NOT use call or call_v here when directly dealing with data without sanatizing your data first. Ideally don't use it at all unless you really kno
This is mentioned below and doesn't need to be here.

2024-12-07 18:51 UTC, Gramps commented on docs/tutorials/p2p.md
> +				print("Packet: " + message.payload)
Please use string substitutions.

2024-12-07 18:51 UTC, Gramps commented on docs/tutorials/p2p.md
> +       				#make data readable. Do NOT use bytes2var with_objects enabled.
Please put spaces after # and capitalize first words for readability.

2024-12-07 18:51 UTC, Gramps commented on docs/tutorials/p2p.md
> +				# Append logic here to deal with message data. Do NOT use call or call_v here when directly dealing with data without sanatizing your data first. Ideally don't use it at all unless you really kno
This becomes redundant with the below explanations.

2024-12-07 18:51 UTC, Gramps commented on docs/tutorials/p2p.md
> +				print("Message: " + message.payload)
Please use string substitutions.

2024-12-07 18:51 UTC, Gramps commented on docs/tutorials/p2p.md
> +If the packet size is greater than zero then it will get the sender's Steam ID and the data they sent. The line `bytes2var` (Godot 2x., 3.x) or `bytes_to_var` (Godot 4.x) is very important as it deco
This probably needs re-written with more specifics and examples as to how and why.

2024-12-07 18:51 UTC, Gramps commented on docs/tutorials/p2p.md
> +	func send_message(this_target: int, packet_data: Dictionary) -> void:
I use a more updated version of this send message like this:
```
func send_packet(packet_data: Dictionary) -> void:
	var sending_packet: PackedByteArray = []
	sending_packet.append_array(var_to_bytes(packet_data).compress(FileAccess.COMPRESSION_GZIP))
	if is_player_host():
		for this_player in lobby_members.keys():
			if this_player != steam_id:
				if not Steam.sendMessageToUser(this_player, sending_packet, Steam.NETWORKING_SEND_RELIABLE, channel_client) == Steam.RESULT_OK:
					print("Failed to send Mesages host packet to %s: %s" % [this_player, sending_packet])
	else:
		if not Steam.sendMessageToUser(Steam.getLobbyOwner(lobby_id), sending_packet, Steam.NETWORKING_SEND_RELIABLE, channel_host) == Steam.RESULT_OK:
			print("Failed to send Messages client packet to %s: %s" % [Steam.getLobbyOwner(lobby_id), sending_packet])
```
Though I think some of it needs explained with updates to the lobby tutorial.

2025-01-14 01:46 UTC, BrianBHuynh commented on docs/tutorials/p2p.md
> +	func send_message(this_target: int, packet_data: Dictionary) -> void:
Ah this relays all the packets through the host right? I think the old code might work better for true peer to peer (instead of one assuming a host identity and everyone else being the clients)

2025-01-14 02:01 UTC, BrianBHuynh commented on docs/tutorials/p2p.md
> +For 'send_type' values please refer to this section of the [SteamWorks Api](https://partner.steamgames.com/doc/api/steamnetworkingtypes#message_sending_flags), these can also be called with their cor
I couldn't find the section for this, if need be I will make a section within the messages documentation in the future or include it in the P2P tutorial.

2025-01-15 22:06 UTC, Gramps approved these changes

2025-01-15 22:06 UTC, Gramps commented
Ayyy! Looking good!  Is this everything?  Should it be pushed live?

2025-01-17 05:00 UTC, BrianBHuynh commented
Yes :D

2025-01-17 05:58 UTC, merged